config:
  document-service: ${URL_DOCUMENT:http://document-service:8081}
  archiving-service: ${URL_ARCHIVE:http://archiving-service:8082}
  notification-service: ${URL_NOTIFICATION:http://notification-service:8083}

resilience4j:
  circuitbreaker:
    instances:
      aggregationService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1

server:
  port: ${PORT:8077}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springboot-app
            client-secret: ${CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope:
              - openid
              - profile
              - email
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/apiintegration

      resourceserver:   # ✅ conservé
        jwt:            # ✅ conservé
          issuer-uri: http://localhost:8080/realms/apiintegration # ✅ seule option retenue

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ma_db
    username: postgres
    password: secret
    pool:
      initial-size: 5
      max-size: 20

  application:
    name: aggregator-service
