config:
  document-service: ${URL_DOCUMENT:http://document-service:8081}
  archiving-service: ${URL_ARCHIVE:http://archiving-service:8082}
  notification-service: ${URL_NOTIFICATION:http://notification-service:8083}

resilience4j:
  circuitbreaker:
    instances:
      aggregationService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/assurance-realm
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ma_db
    username: postgres
    password: secret
    pool:
      initial-size: 5
      max-size: 20
  application:
    name: aggregator-service

server:
  port: ${port:8077}





